[[libpng]]
arch = "x86_64"
git-tree-sha1 = "f5954a72c9f5e595d55507a5002ede8c705b822c"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "2fecf01db428d988383ed8042690e98732d58eb358c52192db685c5a3bcb4dc0"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.x86_64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "314dafbb35245833a73970798547877077c4a0c6"
os = "macos"

    [[libpng.download]]
    sha256 = "5f5c79ecb53375c33a6d7a0e000caac2193e1a0a7ab73a99b801ffa538436d66"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.x86_64-apple-darwin14.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "aa5fc998e92fe7152bb5914df9b3c5d3e5b6ca5c"
os = "windows"

    [[libpng.download]]
    sha256 = "e4bc4bcae51a078a3021762e4d432637f72c16bc8c4f6ed46254aa3ff8489961"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.i686-w64-mingw32.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "85b29b824c500096dbbc464214ccc6107707b5f5"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "0d03a679f08d40b5a64b0eeb83e48ddbd94aaf8dea5458ccf3e6e127aabccca9"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.aarch64-linux-gnu.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "31f6650ad1b540c7c594ce6155ff33cc9765c5b7"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "1b53c6e8be486356e9da931d398a4d3d5c7a2b0986f3dcead457e25184852db9"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.i686-linux-musl.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "7009d7b64ba3bece4facce653c5438a29286acb5"
os = "windows"

    [[libpng.download]]
    sha256 = "1c40afbaba9fd4943624da4a269f69927ca819108d9509cad53888fce67ec8f4"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.x86_64-w64-mingw32.tar.gz"
[[libpng]]
arch = "powerpc64le"
git-tree-sha1 = "6b1567919488a4a8a8dc7e5a8021eacd0838f302"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "d8169a54a69b8964180777de7521dece4db6f41f5f50bcdcf72d80f10a3e18a0"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.powerpc64le-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "bebf576be884d18678cb729dbfed366c088f2fa9"
os = "freebsd"

    [[libpng.download]]
    sha256 = "4b084043e6ea5d0fdf67e12fa21037a9bc3823218e000e4ca38725b03c0a2749"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.x86_64-unknown-freebsd11.1.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "f7d9bad069650ed909666abc2c1d1d03696bd4ac"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "26032584e8c1d5081ca01ca3f54cce9535ad3e82ac9fa8844351097696d5fd7c"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.arm-linux-musleabihf.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "960b3399d926e32663dfc4a7a9f4ead4d69a4c91"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "ae469092b5414bed3771536a553a1060e5a842cff5a5f8dfdc8006921cb38e34"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.aarch64-linux-musl.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "02fd1ac49bf1cbe5577d041be850f8033813e703"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "9c0e4dfd024814dcf9ebeb7d64db82631d7740c37c2a8c8cf9af8fda5bcb2a17"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.i686-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "217405e9e4e65a2d79b6a0d117aa252089046a7d"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "db00766f25113387efaa1e28ce3f424654cb7608858013d4529413a0ff763977"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.x86_64-linux-musl.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "553b72e413d8878d5a5c5e13899559a29f6d7de3"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "49cc191076f049495bdfd31f0daa2cad4f75722fc23f8a50f57adb01b96b0e85"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+1/libpng.v1.6.37.arm-linux-gnueabihf.tar.gz"
