[[libpng]]
arch = "x86_64"
git-tree-sha1 = "6050276fc4ac417dd2c18afd7117017500d0a002"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "392bae7f59ff275333bd140bcfac7c4cac8f33e1c730289d4b6728858e3ced0b"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.x86_64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "69a389125e8c95f23d01c3e60c276eb1bf67b2e8"
os = "macos"

    [[libpng.download]]
    sha256 = "ae8a720b17c335a11c03c1108bfbab40e6533405412a95d04a6462f0d73db80a"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.x86_64-apple-darwin14.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "96f967f742a4deecb84d60887f56343611e96caa"
os = "windows"

    [[libpng.download]]
    sha256 = "49f58066cfa86f57412d1110aa5a2dfe055e5b0e83003c260690eb6300bc89b8"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.i686-w64-mingw32.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "124141e8afba3d6ba8ad128a0ee61aea4abc7c11"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "678ba1bf88d1dffe1e3ae7800584d03496dd73bfcb0bc73d777190acf9a03784"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.aarch64-linux-gnu.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "770732830e8e061b8fb40c6ee21b4e97c0933309"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "cb23ac8d67b1dee6177c858c21e10c63a14845c92731f762eb6ff2b679676139"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.i686-linux-musl.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "e6b281bdfec79e5de0ce5deb9ed83565b3a8faac"
os = "windows"

    [[libpng.download]]
    sha256 = "141348420d73a513f84c601cf9405edfd6a8247cb044337b6c84acda0b73798e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.x86_64-w64-mingw32.tar.gz"
[[libpng]]
arch = "powerpc64le"
git-tree-sha1 = "a670c818bb3d2bf9499e419838edbac803b2ef79"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "ec39e4e94f46cce543e0beec857fac9600b246faee18318006508bed9413c22b"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.powerpc64le-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "a6df8f7826167c04da28f0923cc67498dc8fb72a"
os = "freebsd"

    [[libpng.download]]
    sha256 = "be9a855e76f7ca2ea89c9ebe8400320446baa370192e4d6d3289fee97b06f2a2"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.x86_64-unknown-freebsd11.1.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "e5c4514db0fb0916e8559f7a186f3c778688fae2"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "154f539562faac72206cb1079b1a4736dd17d6715e21ee0842def229f9ba0388"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.arm-linux-musleabihf.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "be2c4a4e73d3fcacdb217c99ee9e0965b09cfdad"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "eea6b90c5ede72e2603d47e2ded88ab76068bc6d5560011f6ef5e53c8a513aac"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.aarch64-linux-musl.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "c004e6fed15ebc6d89f49a23fb4f81d8cdef6fba"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "256a8f4ab6b6dcdc6619dafc113d41f388d7edc1334b0e9be6c685a8b2e07c4f"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.i686-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "44bbe13b95b2a47e2f2d2f1ac91bb5731c542c5d"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "0dee7473b9f996234e0d179b69ec6a45f60ee0df15e901d9f34249d84382dbe4"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.x86_64-linux-musl.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "ae0a86d4c63bda03026e42ddea51a23f1e2e7eb9"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "412a8c95f69c530d1250cd968ef4b10cbca3bac201aff8851bbf63dae4d0cee8"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+0/libpng.v1.6.37.arm-linux-gnueabihf.tar.gz"
