[[libpng]]
arch = "x86_64"
git-tree-sha1 = "af54465408e1f0420fa4789eb71afb34e0a51e26"
os = "macos"

    [[libpng.download]]
    sha256 = "5b05a33d34bcdb7b73268df8f1e35d13d1ed9c8414f7c6af1c035603b317e0d6"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.x86_64-apple-darwin14.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "209224b3b4d20725dff6f0993c3a5b2c2b5601a3"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "8c3c4823f2e647a1eac8e9a5d88980f83ec281b85980605efaad3586cb90a427"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.i686-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "17f6d73840d32d7e16c093840cf71ed592b64593"
os = "freebsd"

    [[libpng.download]]
    sha256 = "f11e31529b9d6e058e4c0ad3e1ca9f992468f6d11134963bcae67a4c681c7907"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.x86_64-unknown-freebsd11.1.tar.gz"
[[libpng]]
arch = "powerpc64le"
git-tree-sha1 = "5a7b92afce161ec35b10dcef1ca7df885516c105"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "deb698d5ab1c4122f9c79889889cd7024ab32bfb996de5f38d9378719bafb2d7"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.powerpc64le-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "4d3e0cccd28a07af5739e46f985921d68a6ed083"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "fa18c305af636121e5970ca0a621dee52bfbafe9369ae827a04ef77afb95cc5e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.x86_64-linux-musl.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "bfc32b726c12b08b849b1cb36cf4b399c4464967"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "035f4f67cb8063ea21d27b98eb98ebe9a05d16a39368f9b6345108a89649a07f"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.x86_64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "41065eb36ee97efe783b2b1ca6493e939a41c14a"
os = "windows"

    [[libpng.download]]
    sha256 = "7d4b74fd4ee2e4b92521145640d837150567930509c672fed3954bd508b483e1"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.x86_64-w64-mingw32.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "d60246133ec1dd847b0b83eda6a3dbe342737933"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "77ae2e8d6c53a0616e56adad59de764dae0164bf592c2604980e6d1afc6e48ad"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.aarch64-linux-musl.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "9b0ace645171eabb3f2a335a75293a1ff1435d90"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "1850c5490990400a3db3970820d0d75b7c2fd1ff1bbe197aa6fbe3885aac3d1c"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.arm-linux-gnueabihf.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "db1180ec25b9032d838988f498b2222905834360"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "43ae5a8c19daecacfcd32283f8e8c7797b2810beba8f7368316b846317cad627"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.i686-linux-musl.tar.gz"
[[libpng]]
arch = "armv7l"
git-tree-sha1 = "4e87959397e5173b5b3ce26fe2c3dd15937952ac"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "d268d72f50be146d8abf05c9f8460c85b6a4826333457d9c41af625cafdb502d"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.arm-linux-musleabihf.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "1588031a5f266fa0f5d92bed9d5d1fe8da050cd4"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "b9929971e7b828dbbc8fa51f9d7bd8a00dd3f88dfe3c89ceaecc9422381faf1d"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.aarch64-linux-gnu.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "fb401a3c8ae01827dd5e404e5293fa41bd3582a2"
os = "windows"

    [[libpng.download]]
    sha256 = "693630517d1710391eadd7d28144e4832fb411165f4992af491e37fa7f6f0073"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.37+2/libpng.v1.6.37.i686-w64-mingw32.tar.gz"
